server:
  port: 8080

spring:
  application:
    name: jwt-auth
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pub
