server:
  port: 8080

spring:
  application:
    name: jwt-auth
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pub

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    display-request-duration: true
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
